# Generated by Django 4.2.4 on 2023-10-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='country',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='city',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='country',
            new_name='department',
        ),
    ]
