# Generated by Django 4.2.4 on 2023-10-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_rename_city_course_rename_country_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default='20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateField(default='1994-12-2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='e_mail',
            field=models.EmailField(default='abc@gail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.IntegerField(default='98564123'),
            preserve_default=False,
        ),
    ]
