# Generated by Django 4.2.4 on 2023-10-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_person_address_person_age_person_dob_person_e_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='purpose',
            field=models.BooleanField(choices=[(1, 'Place Order'), (2, 'Return')], default='1'),
            preserve_default=False,
        ),
    ]
