# Generated by Django 4.2.4 on 2023-10-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_person_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='purpose',
            field=models.BooleanField(choices=[(0, 'Enquiry'), (1, 'Place Order'), (2, 'Return')], default=False),
        ),
    ]
