# Generated by Django 4.2.4 on 2023-10-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_remove_person_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateTimeField(),
        ),
    ]
