# Generated by Django 4.2.4 on 2023-10-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_alter_person_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
