# Generated by Django 4.2.4 on 2023-10-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='purpose',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
