# Generated by Django 4.2.4 on 2023-10-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_person_purpose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='purpose',
            new_name='materials_provided',
        ),
    ]
