# Generated by Django 4.2.4 on 2023-10-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_rename_purpose_person_materials_provided'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='purpose',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
