# Generated by Django 4.2.4 on 2023-10-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0011_person_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
